from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from evaluate_calcium_accuracy import summarize_calcium_accuracy


PROJECT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS_PATH = PROJECT_DIR / "dev" / "artifacts" / "test_recommendation_results.csv"
DEFAULT_OUTPUT_PATH = PROJECT_DIR / "dev" / "artifacts" / "calcium_acceptance_judgement.json"


def _safe_divide(numerator: int, denominator: int) -> float | None:
    if denominator == 0:
        return None
    return float(numerator / denominator)


def _build_check(name: str, actual: float | None, threshold: float, comparator: str) -> dict[str, object]:
    if actual is None:
        passed = False
    elif comparator == "<=":
        passed = actual <= threshold
    elif comparator == ">=":
        passed = actual >= threshold
    else:
        raise ValueError(f"Unsupported comparator: {comparator}")

    return {
        "name": name,
        "actual": actual,
        "comparator": comparator,
        "threshold": threshold,
        "passed": bool(passed),
    }


def judge_acceptance(
    summary: dict[str, object],
    *,
    mae_threshold: float,
    p90_threshold: float,
    max_threshold: float,
    in_spec_range_ratio_threshold: float,
    success_ratio_threshold: float,
) -> dict[str, object]:
    successful_samples = int(summary["successful_samples"])
    evaluated_samples = int(summary["evaluated_samples"])
    success_ratio = _safe_divide(successful_samples, evaluated_samples)

    overall = summary["overall"]
    in_spec_only = summary["in_spec_only"]
    checks = [
        _build_check("success_ratio", success_ratio, success_ratio_threshold, ">="),
        _build_check("overall_mean_abs_error", overall["mean_abs_error"], mae_threshold, "<="),
        _build_check("overall_p90_abs_error", overall["p90_abs_error"], p90_threshold, "<="),
        _build_check("overall_max_abs_error", overall["max_abs_error"], max_threshold, "<="),
        _build_check(
            "in_spec_inside_recommended_range_ratio",
            in_spec_only["inside_recommended_range_ratio"],
            in_spec_range_ratio_threshold,
            ">=",
        ),
    ]
    overall_passed = all(check["passed"] for check in checks)

    return {
        "overall_passed": overall_passed,
        "thresholds": {
            "success_ratio_threshold": success_ratio_threshold,
            "mae_threshold": mae_threshold,
            "p90_threshold": p90_threshold,
            "max_threshold": max_threshold,
            "in_spec_range_ratio_threshold": in_spec_range_ratio_threshold,
        },
        "checks": checks,
        "summary_snapshot": summary,
        "conclusion": (
            "The calcium recommendation logic meets the current acceptance thresholds."
            if overall_passed
            else "The calcium recommendation logic does not meet the current acceptance thresholds."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Judge whether the calcium recommendation logic meets acceptance thresholds.")
    parser.add_argument("--results", default=str(DEFAULT_RESULTS_PATH), help="Path to the offline replay csv generated by projects/T90/test.py.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT_PATH), help="JSON output path for the pass/fail judgement.")
    parser.add_argument("--mae-threshold", type=float, default=0.05, help="Maximum allowed overall calcium MAE.")
    parser.add_argument("--p90-threshold", type=float, default=0.10, help="Maximum allowed overall calcium P90 absolute error.")
    parser.add_argument("--max-threshold", type=float, default=0.25, help="Maximum allowed overall calcium worst-case absolute error.")
    parser.add_argument(
        "--in-spec-range-ratio-threshold",
        type=float,
        default=0.55,
        help="Minimum required ratio for in-spec samples falling inside the recommended calcium range.",
    )
    parser.add_argument(
        "--success-ratio-threshold",
        type=float,
        default=1.0,
        help="Minimum required ratio of successful recommendations over evaluated samples.",
    )
    args = parser.parse_args()

    results_path = Path(args.results)
    if not results_path.exists():
        raise FileNotFoundError(
            f"Results file not found: {results_path}. Please run `python projects/T90/test.py` first."
        )

    results = pd.read_csv(results_path)
    summary = summarize_calcium_accuracy(results)
    judgement = judge_acceptance(
        summary,
        mae_threshold=args.mae_threshold,
        p90_threshold=args.p90_threshold,
        max_threshold=args.max_threshold,
        in_spec_range_ratio_threshold=args.in_spec_range_ratio_threshold,
        success_ratio_threshold=args.success_ratio_threshold,
    )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(judgement, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(judgement, ensure_ascii=False, indent=2))
    print(f"judgement_saved_to={output_path}")


if __name__ == "__main__":
    main()
